# Generated by Django 2.0.2 on 2018-02-27 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_name', models.CharField(max_length=100)),
                ('discipline_department_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.Department')),
            ],
            options={
                'db_table': 'Disciplines',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_full_name', models.CharField(default=None, max_length=200)),
                ('student_university_group', models.CharField(default=None, max_length=10)),
                ('student_faculty', models.CharField(default=None, max_length=15)),
                ('student_grade', models.IntegerField(default=None)),
                ('student_state', models.CharField(blank=True, default=None, max_length=100)),
                ('student_notes', models.TextField(blank=True, default=None)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_full_name', models.CharField(default=None, max_length=200)),
                ('teacher_check_tests', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='TeacherRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_rank', models.CharField(max_length=100)),
            ],
            options={
                'db_table': "Teacher's ranks",
            },
        ),
        migrations.CreateModel(
            name='Troop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('troop_id', models.IntegerField(default=None)),
                ('troop_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.Department')),
                ('troop_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.Teacher')),
                ('troop_head_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.TeacherRank')),
            ],
            options={
                'db_table': 'Troops',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.TeacherRank'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.Teacher'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_head_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.TeacherRank'),
        ),
    ]
