# Generated by Django 2.0.2 on 2018-02-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_teacher_teacher_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Кафедри'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Предмети'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студенти'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Викладачі'},
        ),
        migrations.AlterModelOptions(
            name='teacherrank',
            options={'verbose_name': 'Звання викладачів'},
        ),
        migrations.AlterModelOptions(
            name='troop',
            options={'verbose_name': 'Взводи'},
        ),
    ]
