# Generated by Django 2.0.2 on 2018-02-27 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0004_auto_20180227_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troop',
            name='troop_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.Department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='troop',
            name='troop_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.Teacher', verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='troop',
            name='troop_head_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='control_panel.TeacherRank', verbose_name='Звання Куратора'),
        ),
        migrations.AlterField(
            model_name='troop',
            name='troop_id',
            field=models.IntegerField(default=None, verbose_name='Номер взводу'),
        ),
    ]
